### ISSUE TITLE
One metadata

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#15]
https://github.com/nasa/utm-docs/blob/bcf62206ed3e96b4e518d2dc45b2375e9db29a75/TCL4%20Data%20Management/utm-tcl4-dmp-con1.yaml#L509

Decide with team if we should be referencing https://github.com/nasa/utm-apis/blob/master/utm-domains/utm-domain-metadata.yaml directly instead of re-writing.  I think we'd want to just reference the one definition to ensure consistency between systems.  If the utm-domains metadata needs changes for DMP support, let's add issues there.

**Comment by akishiha** [comment]
we agree to have separate meta data models where it makes sense
