### ISSUE TITLE
Add "all_messages_within_spec" field to USSNegotiations

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#16]
Add a boolean field that indicates the USS believes all messages were exchanged within the negotiations spec.  Note that this value may be `true` while `conflict_resolved` may be false.  We are trying to capture if the negotiation exchange did the right thing from the USS perspective.

I am open to a better name for this field than "all_messages_within_spec".

https://github.com/nasa/utm-docs/blob/bcf62206ed3e96b4e518d2dc45b2375e9db29a75/TCL4%20Data%20Management/utm-tcl4-data-collection.yaml#L322

**Comment by issmith1** [comment]
what is priority of this?
we have 2 assignees who should get it done when?

**Comment by nasajoey** [comment]
@issmith1 please confer with @akishiha and decide best way to address.  Agree it should be just one of you responsible.

**Comment by issmith1** [comment]
is this prospective field Optional or Required?

**Comment by akishiha** [comment]
see: https://github.com/nasa/utm-docs/pull/45
