### ISSUE TITLE
Flight specific AND general range data in same model?

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#20]
https://github.com/nasa/utm-docs/blob/5b9dee929df7215d611cac6d0360fedc632889ca/TCL4%20Data%20Management/utm-tcl4-dmp-con1.yaml#L41

I don't understand CON1.  All properties are required.  There are properties like "actualBvlosLandingPoint" as well as properties like "flightTestRangePolygonPoint_deg".  And the metadata model which is required infers a single operation.  So every operation has to submit a full description of the range?  And if there are no rooftop landings, these data MUST still be included?  Much of this doesn't make sense to me.  Am I missing something?

**Comment by akishiha** [comment]
con has been (is being) reorganized - models no longer reflect this view point
for landings please see: 
commit 272608ba6a87469291b0a74efc8f35239d4d2671
