### ISSUE TITLE
authorship of DMP models

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#24]
https://github.com/nasa/utm-docs/blob/5b9dee929df7215d611cac6d0360fedc632889ca/TCL4%20Data%20Management/utm-tcl4-dmp-con2.yaml#L9

I'd prefer the appropriate author be listed for models I didn't write.  I know this was probably a cut-paste thing, but should fix.

**Comment by akishiha** [comment]
changed to appropriate email contacts.
