### ISSUE TITLE
CON models repetition, grouping

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#25]
I'm unclear in general on the CON models.  It seems like these were written as if operations were part of the "CON" tests from TCL3 and not as more generalized for TCL4.  Is this why there is so much repetition?  Like each operation is expected to be in exactly one of the CONs?  So they'd only submit CON2 and none of the CONs for example?

If that is true, what constitutes CON2 participation?  That is not at all how the scenarios are set up.

Please correct my understanding.

**Comment by akishiha** [comment]
@dmulfinger and i are completely redesigning this

**Comment by akishiha** [comment]
will close and request review in new con PR
