### ISSUE TITLE
Array of coords in CNS?

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#27]
https://github.com/nasa/utm-docs/blob/5b9dee929df7215d611cac6d0360fedc632889ca/TCL4%20Data%20Management/utm-tcl4-dmp-cns.yaml#L81

Is this coords property supposed to be an array?  Isn't this sampling of truth position over the entire operation?  Looks like a single position is required and not an array.

**Comment by akishiha** [comment]
correct.  addressed in https://github.com/nasa/utm-docs/pull/30
