### ISSUE TITLE
CNS latency measure, single value?

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#28]
https://github.com/nasa/utm-docs/blob/5b9dee929df7215d611cac6d0360fedc632889ca/TCL4%20Data%20Management/utm-tcl4-dmp-cns.yaml#L114

Both latency properties in CNS model seem to be single values.  Is this supposed to be a calculated average over the course of the operation?  The equipment's reported specs?  Or is it supposed to be an array of samples taken during the operation?

**Comment by akishiha** [comment]
this was changed on 2019-02-27
see https://docs.google.com/spreadsheets/d/1Fwz6nQTXHZpSDpjxpgai0lqsCnmoaXs7NVTSK0cLzio/edit#gid=1803663489

change was implemented.

Description is more precise now.
