### ISSUE TITLE
CNS landing outcome should be array?

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#29]
https://github.com/nasa/utm-docs/blob/5b9dee929df7215d611cac6d0360fedc632889ca/TCL4%20Data%20Management/utm-tcl4-dmp-cns.yaml#L99

There can be multiple landings, right?  So this should be an array?  This happens in several other spots... I think I have another issue open with another example in this model.

Am I misunderstanding how this is designed to work?  I thought this was written to expect a SINGLE CNS model per operation.  So we'd need arrays of things to capture multiple instances.  Or are you expecting multiple CNS models per operation to be submitted, thus not needing arrays inside of them?  If that is the case, they are required to duplicate the documentation for each instance which seems wrong.  I guess I'm just confused... hopefully just oversight regarding the need to make things arrays?

**Comment by akishiha** [comment]
issue fixed in https://github.com/nasa/utm-docs/pull/30

This is a domain.  the API will make this precise on how data models will be submitted.
