### ISSUE TITLE
Dynamic waypoints?

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-docs#44]
https://github.com/nasa/utm-docs/blob/23d170472059ea3d9eb626e6580ea809fb38f9cf/TCL4%20Data%20Management/utm-tcl4-dmp-aircraft-flightplan.yaml#L17

@akishiha how do we handle dynamic waypoints?  This model assumes preflight, non-changing list of waypoints I think.

**Comment by nasajoey** [comment]
Do we assume timestamp covers this?  Later submissions (during operation) are assumed to be an updated set of waypoints?  Or do we need an additional field:

waypoint_collection_index: 
  description: >-
     For sets of waypoints that are dynamically defined, this index indicates the order in which each set was created.  An initial plan would be 1, a dynamic update would then be 2, etc.   with a full set of waypoints defined with their own set of 
   type: integer
   minimum: 1
   maximum: 9999

Thoughts?  I may be missing something, so any clarification would be welcome.

**Comment by akishiha** [comment]
This model can accommodate dynamic waypoints even though we have organized it under the preflight banner. 

The primary key here is the waypoint_sequence_id a uuid.  

We only support post and deletes.  To accommodate a new waypoint for a particular (call,run) it is just another post during flight.  To accommodate a change in waypoints for a particular (call,run), it is a delete of waypoint_sequence_id followed by a new post.

**Comment by akishiha** [comment]
Note that in the final implementation we are saving all raw HTTP communications on S3 so all of this can be reconstructed if needed.

**Comment by nasajoey** [comment]
seems good.  Thanks.
